version: "2"

volumes:
  cache:

services:
    application:
        build: docker/containers/application
        volumes:
            - ./:/var/www/symfony
            - cache:/var/www/symfony/var/cache
        tty: true
        networks:
            kreactive: ~

    php:
        build: docker/containers/php
        env_file:
            - .env
        volumes_from:
            - application
        links:
            - mysql:mysql
        working_dir: /var/www/symfony
        networks:
            kreactive: ~
        extra_hosts:
            - '${HOSTNAME}:172.${IP_ADDR}.0.21'

    apache:
        build: docker/containers/apache
        env_file:
            - .env
        links:
            - php:php
        volumes_from:
            - application
        volumes:
            - ./docker/logs/apache/:/var/log/apache2
        ports:
            - ${APACHE_PORT}:80
        networks:
            kreactive:
                ipv4_address: 172.${IP_ADDR}.0.21

    mysql:
        build: docker/containers/mysql
        restart: always
        ports:
            - ${MYSQL_PORT}:3306
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_PASSWORD=root
            - MYSQL_USER=root
            - MYSQL_DATABASE=kreactive
        networks:
            kreactive:
                ipv4_address: 172.${IP_ADDR}.0.22

networks:
    kreactive:
        driver: bridge
        ipam:
            config:
                - subnet: 172.${IP_ADDR}.0.0/16
                  gateway: 172.${IP_ADDR}.0.1
